/**
 * Generates docs/demo.svg — an animated terminal demo for the README.
 *
 * An animated SVG rather than a GIF, on purpose: it is a text file (a few kB
 * instead of a few MB), it stays crisp on any display, it renders on GitHub and
 * npm, and it is regenerated by running this script rather than by re-recording
 * a screen. The traffic light is a drawn circle, not an emoji, so it looks the
 * same everywhere.
 *
 *   node demo/make-demo.mjs > docs/demo.svg
 */

const W = 900, H = 396, PAD = 26, LINE = 22, TOP = 74;
const FONT = 'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace';

const C = {
  bg: '#0d1117', chrome: '#161b22', border: '#30363d',
  text: '#c9d1d9', dim: '#6e7681', prompt: '#58a6ff',
  green: '#3fb950', yellow: '#d29922', red: '#f85149', white: '#f0f6fc'
};

const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/** A frame is a list of lines; a line is a list of {t, fill, bold} spans. */
const frames = [
  [
    [{ t: '$ ', fill: C.prompt }, { t: 'npm i -g claude-for-poor-folks && claude-for-poor-folks init', fill: C.text }],
    [],
    [{ t: '  claude-for-poor-folks ', fill: C.white, bold: true }, { t: '— budget gate for ', fill: C.dim }, { t: 'payments-api', fill: C.text }],
    [{ t: '  Asked once per repo. Everything stays local.', fill: C.dim }],
    [],
    [{ t: '  1) Default profile for this repo (or blank = auto): ', fill: C.text }, { t: 'auto', fill: C.green }],
    [{ t: '  2) Session budget in USD (blank = profile default):  ', fill: C.text }, { t: 'profile', fill: C.green }],
    [{ t: '  3) When a limit is hit — warn / ask:                 ', fill: C.text }, { t: 'warn', fill: C.green }],
    [],
    [{ t: '  saved ', fill: C.green }, { t: '.poor-folks.json', fill: C.dim }]
  ],
  [
    [{ t: '$ ', fill: C.prompt }, { t: 'claude', fill: C.text }],
    [],
    [{ t: '> fix the crash in auth.ts when the token expires', fill: C.text }],
    [],
    [{ t: '  [poor-folks] task looks like "Small bug fix" (fix, crash)', fill: C.dim }],
    [{ t: '               — cap $0.50. No question asked.', fill: C.dim }],
    [],
    [{ dot: C.green }, { t: '  $0.02/$0.50 ', fill: C.green }, { t: 'bugfix · ctx 8% · 5h 21%', fill: C.dim }]
  ],
  [
    [{ t: '$ ', fill: C.prompt }, { t: 'claude', fill: C.text }],
    [],
    [{ t: '> fix the crash in auth.ts when the token expires', fill: C.text }],
    [],
    [{ t: '  ● Read auth.ts, token.ts, session.test.ts', fill: C.dim }],
    [{ t: '  ● Bash(npm test) — 3 failing', fill: C.dim }],
    [],
    [{ dot: C.green }, { t: '  $0.19/$0.50 ', fill: C.green }, { t: 'bugfix · ctx 31% · 5h 22% · $0.11/m', fill: C.dim }]
  ],
  [
    [{ t: '$ ', fill: C.prompt }, { t: 'claude', fill: C.text }],
    [],
    [{ t: '  ● Bash(npm test) — 3 failing', fill: C.dim }],
    [{ t: '  ● Edit auth.ts · Bash(npm test) — 3 failing', fill: C.dim }],
    [{ t: '  ● Edit auth.ts · Bash(npm test) — 3 failing', fill: C.dim }],
    [],
    [{ t: '  [poor-folks]', fill: C.yellow }],
    [{ t: '  ! 80% of budget used — $0.41 of $0.50', fill: C.yellow }],
    [],
    [{ dot: C.yellow }, { t: '  $0.41/$0.50 ', fill: C.yellow }, { t: 'bugfix · ctx 62% · 5h 24% · $0.34/m', fill: C.dim }]
  ],
  [
    [{ t: '$ ', fill: C.prompt }, { t: 'claude', fill: C.text }],
    [],
    [{ t: '  ● Edit auth.ts · Bash(npm test) — 3 failing', fill: C.dim }],
    [{ t: '  ● Edit auth.ts · Bash(npm test) — 3 failing', fill: C.dim }],
    [],
    [{ t: '  [poor-folks]', fill: C.red, bold: true }],
    [{ t: '  !! Burning $0.91/min (limit $0.30/min)', fill: C.red, bold: true }],
    [{ t: '     At this rate the budget is gone in ~0.1 min.', fill: C.text }],
    [{ t: '     -> Usually a retry loop. Check the last minute.', fill: C.text }],
    [],
    [{ dot: C.red }, { t: '  $0.68/$0.50 ', fill: C.red, bold: true }, { t: 'bugfix · ctx 84% · 5h 26% · ', fill: C.dim }, { t: '↑$0.91/m', fill: C.red }]
  ],
  [
    [{ t: '$ ', fill: C.prompt }, { t: 'claude-for-poor-folks report', fill: C.text }],
    [],
    [{ t: '  $4.82 ', fill: C.white, bold: true }, { t: 'across 11 sessions · 3.1M tokens', fill: C.dim }],
    [],
    [{ t: '  refactor   $2.41  ', fill: C.text }, { t: '██████████', fill: C.red }, { t: '░░░░░░░░ 50%', fill: C.dim }],
    [{ t: '  feature    $1.60  ', fill: C.text }, { t: '███████', fill: C.yellow }, { t: '░░░░░░░░░░░ 33%', fill: C.dim }],
    [{ t: '  bugfix     $0.81  ', fill: C.text }, { t: '███', fill: C.green }, { t: '░░░░░░░░░░░░░░░ 17%', fill: C.dim }],
    [],
    [{ t: '  where it leaks', fill: C.white, bold: true }],
    [{ t: '  • Average prompt-cache read ratio: 41% (poor).', fill: C.yellow }],
    [{ t: '    Cache reads cost ~1/10 of fresh input — this is', fill: C.dim }],
    [{ t: '    the single biggest lever on the bill.', fill: C.dim }]
  ]
];

const HOLD = 2.6;                       // seconds each frame is on screen
const TOTAL = frames.length * HOLD;
const pct = t => ((t / TOTAL) * 100).toFixed(3);

function renderLine(spans, y) {
  let x = PAD;
  const out = [];
  for (const s of spans) {
    if (s.dot) {
      out.push(`<circle cx="${x + 5}" cy="${y - 4}" r="5" fill="${s.dot}"/>`);
      x += 14;
      continue;
    }
    const weight = s.bold ? ' font-weight="600"' : '';
    out.push(`<text x="${x}" y="${y}" fill="${s.fill}"${weight}>${esc(s.t)}</text>`);
    x += s.t.length * 8.42;             // measured advance for 14px monospace
  }
  return out.join('');
}

const groups = frames.map((lines, i) => {
  const body = lines.map((spans, j) => (spans.length ? renderLine(spans, TOP + j * LINE) : '')).join('');
  return `<g class="f f${i}">${body}</g>`;
}).join('\n');

// Each frame is opaque for its slot and transparent otherwise, with a short cross-fade.
const css = frames.map((_, i) => {
  const start = i * HOLD;
  const a = pct(start), b = pct(start + 0.18), c = pct(start + HOLD - 0.18), d = pct(start + HOLD);
  return `@keyframes k${i}{0%,${a}%{opacity:0}${b}%,${c}%{opacity:1}${d}%,100%{opacity:0}}
.f${i}{animation:k${i} ${TOTAL}s steps(1,end) infinite;animation-timing-function:ease-in-out}`;
}).join('\n');

process.stdout.write(`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" font-family='${FONT}' font-size="14">
<style>
text{white-space:pre;dominant-baseline:middle}
.f{opacity:0}
${css}
</style>
<rect width="${W}" height="${H}" rx="10" fill="${C.bg}" stroke="${C.border}"/>
<rect width="${W}" height="38" rx="10" fill="${C.chrome}"/>
<rect y="28" width="${W}" height="10" fill="${C.chrome}"/>
<line x1="0" y1="38" x2="${W}" y2="38" stroke="${C.border}"/>
<circle cx="22" cy="19" r="5.5" fill="#ff5f57"/><circle cx="42" cy="19" r="5.5" fill="#febc2e"/><circle cx="62" cy="19" r="5.5" fill="#28c840"/>
<text x="${W / 2}" y="20" fill="${C.dim}" font-size="12" text-anchor="middle">claude-for-poor-folks</text>
${groups}
</svg>
`);
